### PR TITLE
[WIP] Minimal modernization to get things building.

### PR DESCRIPTION
**Pull request by ssfrr**
This is a more minimal start to #21 that updates to using a Project.toml and modernizes the CI config. I also just tagged a release of SampledSignals that should fix the issues with version bounds due to the recent FFTW/DSP switchup. I think this should fix some of the issues that showed up in #21 so we can focus on the new binarybuilder stuff.

### CODE REVIEW

**Comment by ssfrr** [comment]
Appveyor is failing because WinRPM isn't working, but that's probably the state of current master anyways. I think this PR is a strict improvement and should make it easier to finish the BB integration, so I'm leaning towards merging. 

@haberdashPI @danmackinlay @jpsamaroo would you mind testing this out and seeing if it resolves #19 for you?

**Comment by jpsamaroo** [comment]
Tests pass for me locally, and I was able to load the audio to "Never Gonna Give You Up", which I consider a sufficiently difficult test to pass.

**Comment by ssfrr** [comment]
Yes, this was all a cleverly indirect and psychologically-sophisticated rickrolling of @jpsamaroo. Sounds good. I'll merge and tag a release shortly (probably tonight), and then we can figure out the BB stuff.

**Comment by haberdashPI** [comment]
Apologies, I'm still having troubles with Homebrew building on my machine (output below). If I recall correctly, Homebrew properly installs on my work machine, but I am away from the office for a little while—I'm on leave with my newborn son—so cannot easily test this right now.

**Comment by ssfrr** [comment]
Congratulations on the new baby! The beginning is tough but it gets better. :)

Definitely no rush on testing. If you get a minute and want to post the homebrew issue you're seeing to a new issue I can see if I have any ideas. I'd also be curious if anything is different if you use `Pkg.instantiate` to make sure you're using all the same versions as what's listed in the `Manifest.toml` here.

**Pull request merged**
